// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package worker

import (
	"github.com/Sayfargo/gophermart-loyal-service/internal/accrual/goods/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockGoodsCacheGetter creates a new instance of MockGoodsCacheGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGoodsCacheGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGoodsCacheGetter {
	mock := &MockGoodsCacheGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGoodsCacheGetter is an autogenerated mock type for the GoodsCacheGetter type
type MockGoodsCacheGetter struct {
	mock.Mock
}

type MockGoodsCacheGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGoodsCacheGetter) EXPECT() *MockGoodsCacheGetter_Expecter {
	return &MockGoodsCacheGetter_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockGoodsCacheGetter
func (_mock *MockGoodsCacheGetter) Get() []model.GoodsInfo {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 []model.GoodsInfo
	if returnFunc, ok := ret.Get(0).(func() []model.GoodsInfo); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.GoodsInfo)
		}
	}
	return r0
}

// MockGoodsCacheGetter_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockGoodsCacheGetter_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
func (_e *MockGoodsCacheGetter_Expecter) Get() *MockGoodsCacheGetter_Get_Call {
	return &MockGoodsCacheGetter_Get_Call{Call: _e.mock.On("Get")}
}

func (_c *MockGoodsCacheGetter_Get_Call) Run(run func()) *MockGoodsCacheGetter_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGoodsCacheGetter_Get_Call) Return(goodsInfos []model.GoodsInfo) *MockGoodsCacheGetter_Get_Call {
	_c.Call.Return(goodsInfos)
	return _c
}

func (_c *MockGoodsCacheGetter_Get_Call) RunAndReturn(run func() []model.GoodsInfo) *MockGoodsCacheGetter_Get_Call {
	_c.Call.Return(run)
	return _c
}
