// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package handler

import (
	"context"

	"github.com/Sayfargo/gophermart-loyal-service/internal/accrual/goods/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockGoodsService creates a new instance of MockGoodsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGoodsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGoodsService {
	mock := &MockGoodsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGoodsService is an autogenerated mock type for the GoodsService type
type MockGoodsService struct {
	mock.Mock
}

type MockGoodsService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGoodsService) EXPECT() *MockGoodsService_Expecter {
	return &MockGoodsService_Expecter{mock: &_m.Mock}
}

// RegisterGoods provides a mock function for the type MockGoodsService
func (_mock *MockGoodsService) RegisterGoods(ctx context.Context, goods model.GoodsInfo) error {
	ret := _mock.Called(ctx, goods)

	if len(ret) == 0 {
		panic("no return value specified for RegisterGoods")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.GoodsInfo) error); ok {
		r0 = returnFunc(ctx, goods)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGoodsService_RegisterGoods_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterGoods'
type MockGoodsService_RegisterGoods_Call struct {
	*mock.Call
}

// RegisterGoods is a helper method to define mock.On call
//   - ctx context.Context
//   - goods model.GoodsInfo
func (_e *MockGoodsService_Expecter) RegisterGoods(ctx any, goods any) *MockGoodsService_RegisterGoods_Call {
	return &MockGoodsService_RegisterGoods_Call{Call: _e.mock.On("RegisterGoods", ctx, goods)}
}

func (_c *MockGoodsService_RegisterGoods_Call) Run(run func(ctx context.Context, goods model.GoodsInfo)) *MockGoodsService_RegisterGoods_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.GoodsInfo
		if args[1] != nil {
			arg1 = args[1].(model.GoodsInfo)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGoodsService_RegisterGoods_Call) Return(err error) *MockGoodsService_RegisterGoods_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGoodsService_RegisterGoods_Call) RunAndReturn(run func(ctx context.Context, goods model.GoodsInfo) error) *MockGoodsService_RegisterGoods_Call {
	_c.Call.Return(run)
	return _c
}
