// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"context"

	"github.com/Sayfargo/gophermart-loyal-service/internal/gophermart/user/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUserRepository creates a new instance of MockUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepository {
	mock := &MockUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserRepository is an autogenerated mock type for the UserRepository type
type MockUserRepository struct {
	mock.Mock
}

type MockUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepository) EXPECT() *MockUserRepository_Expecter {
	return &MockUserRepository_Expecter{mock: &_m.Mock}
}

// FindUserInfo provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) FindUserInfo(ctx context.Context, userLogin string) (*model.UserInfo, error) {
	ret := _mock.Called(ctx, userLogin)

	if len(ret) == 0 {
		panic("no return value specified for FindUserInfo")
	}

	var r0 *model.UserInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.UserInfo, error)); ok {
		return returnFunc(ctx, userLogin)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.UserInfo); ok {
		r0 = returnFunc(ctx, userLogin)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userLogin)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_FindUserInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindUserInfo'
type MockUserRepository_FindUserInfo_Call struct {
	*mock.Call
}

// FindUserInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - userLogin string
func (_e *MockUserRepository_Expecter) FindUserInfo(ctx any, userLogin any) *MockUserRepository_FindUserInfo_Call {
	return &MockUserRepository_FindUserInfo_Call{Call: _e.mock.On("FindUserInfo", ctx, userLogin)}
}

func (_c *MockUserRepository_FindUserInfo_Call) Run(run func(ctx context.Context, userLogin string)) *MockUserRepository_FindUserInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_FindUserInfo_Call) Return(userInfo *model.UserInfo, err error) *MockUserRepository_FindUserInfo_Call {
	_c.Call.Return(userInfo, err)
	return _c
}

func (_c *MockUserRepository_FindUserInfo_Call) RunAndReturn(run func(ctx context.Context, userLogin string) (*model.UserInfo, error)) *MockUserRepository_FindUserInfo_Call {
	_c.Call.Return(run)
	return _c
}

// SaveUserInfo provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) SaveUserInfo(ctx context.Context, userInfo model.UserInfo) error {
	ret := _mock.Called(ctx, userInfo)

	if len(ret) == 0 {
		panic("no return value specified for SaveUserInfo")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.UserInfo) error); ok {
		r0 = returnFunc(ctx, userInfo)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepository_SaveUserInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveUserInfo'
type MockUserRepository_SaveUserInfo_Call struct {
	*mock.Call
}

// SaveUserInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - userInfo model.UserInfo
func (_e *MockUserRepository_Expecter) SaveUserInfo(ctx any, userInfo any) *MockUserRepository_SaveUserInfo_Call {
	return &MockUserRepository_SaveUserInfo_Call{Call: _e.mock.On("SaveUserInfo", ctx, userInfo)}
}

func (_c *MockUserRepository_SaveUserInfo_Call) Run(run func(ctx context.Context, userInfo model.UserInfo)) *MockUserRepository_SaveUserInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.UserInfo
		if args[1] != nil {
			arg1 = args[1].(model.UserInfo)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_SaveUserInfo_Call) Return(err error) *MockUserRepository_SaveUserInfo_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepository_SaveUserInfo_Call) RunAndReturn(run func(ctx context.Context, userInfo model.UserInfo) error) *MockUserRepository_SaveUserInfo_Call {
	_c.Call.Return(run)
	return _c
}
