// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package handler

import (
	"context"

	"github.com/Sayfargo/gophermart-loyal-service/internal/gophermart/balance/model"
	"github.com/google/uuid"
	"github.com/shopspring/decimal"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBalanceService creates a new instance of MockBalanceService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBalanceService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBalanceService {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockBalanceService{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockBalanceService is an autogenerated mock type for the BalanceService type
type MockBalanceService struct {
	mock.Mock
}

type MockBalanceService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBalanceService) EXPECT() *MockBalanceService_Expecter {
	return &MockBalanceService_Expecter{mock: &_m.Mock}
}

// GetBalance provides a mock function for the type MockBalanceService
func (_mock *MockBalanceService) GetBalance(ctx context.Context, userID uuid.UUID) (model.Balance, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetBalance")
	}

	var r0 model.Balance
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (model.Balance, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) model.Balance); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(model.Balance)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBalanceService_GetBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBalance'
type MockBalanceService_GetBalance_Call struct {
	*mock.Call
}

// GetBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockBalanceService_Expecter) GetBalance(ctx any, userID any) *MockBalanceService_GetBalance_Call {
	return &MockBalanceService_GetBalance_Call{Call: _e.mock.On("GetBalance", ctx, userID)}
}

func (_c *MockBalanceService_GetBalance_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockBalanceService_GetBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBalanceService_GetBalance_Call) Return(balance model.Balance, err error) *MockBalanceService_GetBalance_Call {
	_c.Call.Return(balance, err)
	return _c
}

func (_c *MockBalanceService_GetBalance_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) (model.Balance, error)) *MockBalanceService_GetBalance_Call {
	_c.Call.Return(run)
	return _c
}

// GetWithdrawals provides a mock function for the type MockBalanceService
func (_mock *MockBalanceService) GetWithdrawals(ctx context.Context, userID uuid.UUID) ([]model.Withdrawal, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetWithdrawals")
	}

	var r0 []model.Withdrawal
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]model.Withdrawal, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []model.Withdrawal); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Withdrawal)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBalanceService_GetWithdrawals_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWithdrawals'
type MockBalanceService_GetWithdrawals_Call struct {
	*mock.Call
}

// GetWithdrawals is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockBalanceService_Expecter) GetWithdrawals(ctx any, userID any) *MockBalanceService_GetWithdrawals_Call {
	return &MockBalanceService_GetWithdrawals_Call{Call: _e.mock.On("GetWithdrawals", ctx, userID)}
}

func (_c *MockBalanceService_GetWithdrawals_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockBalanceService_GetWithdrawals_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBalanceService_GetWithdrawals_Call) Return(withdrawals []model.Withdrawal, err error) *MockBalanceService_GetWithdrawals_Call {
	_c.Call.Return(withdrawals, err)
	return _c
}

func (_c *MockBalanceService_GetWithdrawals_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) ([]model.Withdrawal, error)) *MockBalanceService_GetWithdrawals_Call {
	_c.Call.Return(run)
	return _c
}

// Withdraw provides a mock function for the type MockBalanceService
func (_mock *MockBalanceService) Withdraw(ctx context.Context, userID uuid.UUID, orderNum string, sum decimal.Decimal) error {
	ret := _mock.Called(ctx, userID, orderNum, sum)

	if len(ret) == 0 {
		panic("no return value specified for Withdraw")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, decimal.Decimal) error); ok {
		r0 = returnFunc(ctx, userID, orderNum, sum)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBalanceService_Withdraw_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Withdraw'
type MockBalanceService_Withdraw_Call struct {
	*mock.Call
}

// Withdraw is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - orderNum string
//   - sum decimal.Decimal
func (_e *MockBalanceService_Expecter) Withdraw(ctx any, userID any, orderNum any, sum any) *MockBalanceService_Withdraw_Call {
	return &MockBalanceService_Withdraw_Call{Call: _e.mock.On("Withdraw", ctx, userID, orderNum, sum)}
}

func (_c *MockBalanceService_Withdraw_Call) Run(run func(ctx context.Context, userID uuid.UUID, orderNum string, sum decimal.Decimal)) *MockBalanceService_Withdraw_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 decimal.Decimal
		if args[3] != nil {
			arg3 = args[3].(decimal.Decimal)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockBalanceService_Withdraw_Call) Return(err error) *MockBalanceService_Withdraw_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBalanceService_Withdraw_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, orderNum string, sum decimal.Decimal) error) *MockBalanceService_Withdraw_Call {
	_c.Call.Return(run)
	return _c
}
