// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package worker

import (
	"context"

	"github.com/Sayfargo/gophermart-loyal-service/internal/gophermart/order/model"
	"github.com/jackc/pgx/v5"
	"github.com/shopspring/decimal"
	mock "github.com/stretchr/testify/mock"
)

// NewMockOrderStore creates a new instance of MockOrderStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderStore {
	mock := &MockOrderStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOrderStore is an autogenerated mock type for the OrderStore type
type MockOrderStore struct {
	mock.Mock
}

type MockOrderStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderStore) EXPECT() *MockOrderStore_Expecter {
	return &MockOrderStore_Expecter{mock: &_m.Mock}
}

// GetPendingOrders provides a mock function for the type MockOrderStore
func (_mock *MockOrderStore) GetPendingOrders(ctx context.Context) ([]model.Order, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetPendingOrders")
	}

	var r0 []model.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]model.Order, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []model.Order); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderStore_GetPendingOrders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPendingOrders'
type MockOrderStore_GetPendingOrders_Call struct {
	*mock.Call
}

// GetPendingOrders is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockOrderStore_Expecter) GetPendingOrders(ctx any) *MockOrderStore_GetPendingOrders_Call {
	return &MockOrderStore_GetPendingOrders_Call{Call: _e.mock.On("GetPendingOrders", ctx)}
}

func (_c *MockOrderStore_GetPendingOrders_Call) Run(run func(ctx context.Context)) *MockOrderStore_GetPendingOrders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockOrderStore_GetPendingOrders_Call) Return(orders []model.Order, err error) *MockOrderStore_GetPendingOrders_Call {
	_c.Call.Return(orders, err)
	return _c
}

func (_c *MockOrderStore_GetPendingOrders_Call) RunAndReturn(run func(ctx context.Context) ([]model.Order, error)) *MockOrderStore_GetPendingOrders_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOrderResultTx provides a mock function for the type MockOrderStore
func (_mock *MockOrderStore) UpdateOrderResultTx(ctx context.Context, tx pgx.Tx, orderNum string, status model.OrderStatus, accrual *decimal.Decimal) (bool, error) {
	ret := _mock.Called(ctx, tx, orderNum, status, accrual)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrderResultTx")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, pgx.Tx, string, model.OrderStatus, *decimal.Decimal) (bool, error)); ok {
		return returnFunc(ctx, tx, orderNum, status, accrual)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, pgx.Tx, string, model.OrderStatus, *decimal.Decimal) bool); ok {
		r0 = returnFunc(ctx, tx, orderNum, status, accrual)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, pgx.Tx, string, model.OrderStatus, *decimal.Decimal) error); ok {
		r1 = returnFunc(ctx, tx, orderNum, status, accrual)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderStore_UpdateOrderResultTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOrderResultTx'
type MockOrderStore_UpdateOrderResultTx_Call struct {
	*mock.Call
}

// UpdateOrderResultTx is a helper method to define mock.On call
//   - ctx context.Context
//   - tx pgx.Tx
//   - orderNum string
//   - status model.OrderStatus
//   - accrual *decimal.Decimal
func (_e *MockOrderStore_Expecter) UpdateOrderResultTx(ctx any, tx any, orderNum any, status any, accrual any) *MockOrderStore_UpdateOrderResultTx_Call {
	return &MockOrderStore_UpdateOrderResultTx_Call{Call: _e.mock.On("UpdateOrderResultTx", ctx, tx, orderNum, status, accrual)}
}

func (_c *MockOrderStore_UpdateOrderResultTx_Call) Run(run func(ctx context.Context, tx pgx.Tx, orderNum string, status model.OrderStatus, accrual *decimal.Decimal)) *MockOrderStore_UpdateOrderResultTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 pgx.Tx
		if args[1] != nil {
			arg1 = args[1].(pgx.Tx)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 model.OrderStatus
		if args[3] != nil {
			arg3 = args[3].(model.OrderStatus)
		}
		var arg4 *decimal.Decimal
		if args[4] != nil {
			arg4 = args[4].(*decimal.Decimal)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockOrderStore_UpdateOrderResultTx_Call) Return(updated bool, err error) *MockOrderStore_UpdateOrderResultTx_Call {
	_c.Call.Return(updated, err)
	return _c
}

func (_c *MockOrderStore_UpdateOrderResultTx_Call) RunAndReturn(run func(ctx context.Context, tx pgx.Tx, orderNum string, status model.OrderStatus, accrual *decimal.Decimal) (bool, error)) *MockOrderStore_UpdateOrderResultTx_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function for the type MockOrderStore
func (_mock *MockOrderStore) UpdateStatus(ctx context.Context, orderNum string, status model.OrderStatus) error {
	ret := _mock.Called(ctx, orderNum, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, model.OrderStatus) error); ok {
		r0 = returnFunc(ctx, orderNum, status)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrderStore_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockOrderStore_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - orderNum string
//   - status model.OrderStatus
func (_e *MockOrderStore_Expecter) UpdateStatus(ctx any, orderNum any, status any) *MockOrderStore_UpdateStatus_Call {
	return &MockOrderStore_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, orderNum, status)}
}

func (_c *MockOrderStore_UpdateStatus_Call) Run(run func(ctx context.Context, orderNum string, status model.OrderStatus)) *MockOrderStore_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 model.OrderStatus
		if args[2] != nil {
			arg2 = args[2].(model.OrderStatus)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockOrderStore_UpdateStatus_Call) Return(err error) *MockOrderStore_UpdateStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrderStore_UpdateStatus_Call) RunAndReturn(run func(ctx context.Context, orderNum string, status model.OrderStatus) error) *MockOrderStore_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}
