// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package worker

import (
	"context"

	"github.com/Sayfargo/gophermart-loyal-service/internal/gophermart/accrualclient"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAccrualClient creates a new instance of MockAccrualClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccrualClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccrualClient {
	mock := &MockAccrualClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAccrualClient is an autogenerated mock type for the AccrualClient type
type MockAccrualClient struct {
	mock.Mock
}

type MockAccrualClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAccrualClient) EXPECT() *MockAccrualClient_Expecter {
	return &MockAccrualClient_Expecter{mock: &_m.Mock}
}

// GetOrder provides a mock function for the type MockAccrualClient
func (_mock *MockAccrualClient) GetOrder(ctx context.Context, orderNum string) (*accrualclient.ResultResponse, error) {
	ret := _mock.Called(ctx, orderNum)

	if len(ret) == 0 {
		panic("no return value specified for GetOrder")
	}

	var r0 *accrualclient.ResultResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*accrualclient.ResultResponse, error)); ok {
		return returnFunc(ctx, orderNum)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *accrualclient.ResultResponse); ok {
		r0 = returnFunc(ctx, orderNum)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*accrualclient.ResultResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, orderNum)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccrualClient_GetOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrder'
type MockAccrualClient_GetOrder_Call struct {
	*mock.Call
}

// GetOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - orderNum string
func (_e *MockAccrualClient_Expecter) GetOrder(ctx any, orderNum any) *MockAccrualClient_GetOrder_Call {
	return &MockAccrualClient_GetOrder_Call{Call: _e.mock.On("GetOrder", ctx, orderNum)}
}

func (_c *MockAccrualClient_GetOrder_Call) Run(run func(ctx context.Context, orderNum string)) *MockAccrualClient_GetOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccrualClient_GetOrder_Call) Return(resultResponse *accrualclient.ResultResponse, err error) *MockAccrualClient_GetOrder_Call {
	_c.Call.Return(resultResponse, err)
	return _c
}

func (_c *MockAccrualClient_GetOrder_Call) RunAndReturn(run func(ctx context.Context, orderNum string) (*accrualclient.ResultResponse, error)) *MockAccrualClient_GetOrder_Call {
	_c.Call.Return(run)
	return _c
}
