// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"github.com/Sayfargo/gophermart-loyal-service/internal/accrual/order/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockOrderNotifier creates a new instance of MockOrderNotifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderNotifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderNotifier {
	mock := &MockOrderNotifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOrderNotifier is an autogenerated mock type for the OrderNotifier type
type MockOrderNotifier struct {
	mock.Mock
}

type MockOrderNotifier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderNotifier) EXPECT() *MockOrderNotifier_Expecter {
	return &MockOrderNotifier_Expecter{mock: &_m.Mock}
}

// Notify provides a mock function for the type MockOrderNotifier
func (_mock *MockOrderNotifier) Notify(order model.Order) {
	_mock.Called(order)
	return
}

// MockOrderNotifier_Notify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Notify'
type MockOrderNotifier_Notify_Call struct {
	*mock.Call
}

// Notify is a helper method to define mock.On call
//   - order model.Order
func (_e *MockOrderNotifier_Expecter) Notify(order any) *MockOrderNotifier_Notify_Call {
	return &MockOrderNotifier_Notify_Call{Call: _e.mock.On("Notify", order)}
}

func (_c *MockOrderNotifier_Notify_Call) Run(run func(order model.Order)) *MockOrderNotifier_Notify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 model.Order
		if args[0] != nil {
			arg0 = args[0].(model.Order)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockOrderNotifier_Notify_Call) Return() *MockOrderNotifier_Notify_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockOrderNotifier_Notify_Call) RunAndReturn(run func(order model.Order)) *MockOrderNotifier_Notify_Call {
	_c.Run(run)
	return _c
}
