// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package handler

import (
	"context"

	"github.com/Sayfargo/gophermart-loyal-service/internal/accrual/order/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockOrderService creates a new instance of MockOrderService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderService {
	mock := &MockOrderService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOrderService is an autogenerated mock type for the OrderService type
type MockOrderService struct {
	mock.Mock
}

type MockOrderService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderService) EXPECT() *MockOrderService_Expecter {
	return &MockOrderService_Expecter{mock: &_m.Mock}
}

// GetOrder provides a mock function for the type MockOrderService
func (_mock *MockOrderService) GetOrder(ctx context.Context, orderNum string) (model.Order, error) {
	ret := _mock.Called(ctx, orderNum)

	if len(ret) == 0 {
		panic("no return value specified for GetOrder")
	}

	var r0 model.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (model.Order, error)); ok {
		return returnFunc(ctx, orderNum)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) model.Order); ok {
		r0 = returnFunc(ctx, orderNum)
	} else {
		r0 = ret.Get(0).(model.Order)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, orderNum)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderService_GetOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrder'
type MockOrderService_GetOrder_Call struct {
	*mock.Call
}

// GetOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - orderNum string
func (_e *MockOrderService_Expecter) GetOrder(ctx any, orderNum any) *MockOrderService_GetOrder_Call {
	return &MockOrderService_GetOrder_Call{Call: _e.mock.On("GetOrder", ctx, orderNum)}
}

func (_c *MockOrderService_GetOrder_Call) Run(run func(ctx context.Context, orderNum string)) *MockOrderService_GetOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderService_GetOrder_Call) Return(order model.Order, err error) *MockOrderService_GetOrder_Call {
	_c.Call.Return(order, err)
	return _c
}

func (_c *MockOrderService_GetOrder_Call) RunAndReturn(run func(ctx context.Context, orderNum string) (model.Order, error)) *MockOrderService_GetOrder_Call {
	_c.Call.Return(run)
	return _c
}

// UploadOrder provides a mock function for the type MockOrderService
func (_mock *MockOrderService) UploadOrder(ctx context.Context, order model.Order) error {
	ret := _mock.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for UploadOrder")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Order) error); ok {
		r0 = returnFunc(ctx, order)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrderService_UploadOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadOrder'
type MockOrderService_UploadOrder_Call struct {
	*mock.Call
}

// UploadOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - order model.Order
func (_e *MockOrderService_Expecter) UploadOrder(ctx any, order any) *MockOrderService_UploadOrder_Call {
	return &MockOrderService_UploadOrder_Call{Call: _e.mock.On("UploadOrder", ctx, order)}
}

func (_c *MockOrderService_UploadOrder_Call) Run(run func(ctx context.Context, order model.Order)) *MockOrderService_UploadOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.Order
		if args[1] != nil {
			arg1 = args[1].(model.Order)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderService_UploadOrder_Call) Return(err error) *MockOrderService_UploadOrder_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrderService_UploadOrder_Call) RunAndReturn(run func(ctx context.Context, order model.Order) error) *MockOrderService_UploadOrder_Call {
	_c.Call.Return(run)
	return _c
}
