// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package handler

import (
	"context"

	"github.com/Sayfargo/gophermart-loyal-service/internal/gophermart/order/model"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockOrderService creates a new instance of MockOrderService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderService {
	mock := &MockOrderService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOrderService is an autogenerated mock type for the OrderService type
type MockOrderService struct {
	mock.Mock
}

type MockOrderService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderService) EXPECT() *MockOrderService_Expecter {
	return &MockOrderService_Expecter{mock: &_m.Mock}
}

// GetOrders provides a mock function for the type MockOrderService
func (_mock *MockOrderService) GetOrders(ctx context.Context, uid uuid.UUID) ([]model.Order, error) {
	ret := _mock.Called(ctx, uid)

	if len(ret) == 0 {
		panic("no return value specified for GetOrders")
	}

	var r0 []model.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]model.Order, error)); ok {
		return returnFunc(ctx, uid)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []model.Order); ok {
		r0 = returnFunc(ctx, uid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, uid)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderService_GetOrders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrders'
type MockOrderService_GetOrders_Call struct {
	*mock.Call
}

// GetOrders is a helper method to define mock.On call
//   - ctx context.Context
//   - uid uuid.UUID
func (_e *MockOrderService_Expecter) GetOrders(ctx any, uid any) *MockOrderService_GetOrders_Call {
	return &MockOrderService_GetOrders_Call{Call: _e.mock.On("GetOrders", ctx, uid)}
}

func (_c *MockOrderService_GetOrders_Call) Run(run func(ctx context.Context, uid uuid.UUID)) *MockOrderService_GetOrders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderService_GetOrders_Call) Return(orders []model.Order, err error) *MockOrderService_GetOrders_Call {
	_c.Call.Return(orders, err)
	return _c
}

func (_c *MockOrderService_GetOrders_Call) RunAndReturn(run func(ctx context.Context, uid uuid.UUID) ([]model.Order, error)) *MockOrderService_GetOrders_Call {
	_c.Call.Return(run)
	return _c
}

// UploadOrder provides a mock function for the type MockOrderService
func (_mock *MockOrderService) UploadOrder(ctx context.Context, orderNumStr string, uid uuid.UUID) error {
	ret := _mock.Called(ctx, orderNumStr, uid)

	if len(ret) == 0 {
		panic("no return value specified for UploadOrder")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, orderNumStr, uid)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrderService_UploadOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadOrder'
type MockOrderService_UploadOrder_Call struct {
	*mock.Call
}

// UploadOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - orderNumStr string
//   - uid uuid.UUID
func (_e *MockOrderService_Expecter) UploadOrder(ctx any, orderNumStr any, uid any) *MockOrderService_UploadOrder_Call {
	return &MockOrderService_UploadOrder_Call{Call: _e.mock.On("UploadOrder", ctx, orderNumStr, uid)}
}

func (_c *MockOrderService_UploadOrder_Call) Run(run func(ctx context.Context, orderNumStr string, uid uuid.UUID)) *MockOrderService_UploadOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockOrderService_UploadOrder_Call) Return(err error) *MockOrderService_UploadOrder_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrderService_UploadOrder_Call) RunAndReturn(run func(ctx context.Context, orderNumStr string, uid uuid.UUID) error) *MockOrderService_UploadOrder_Call {
	_c.Call.Return(run)
	return _c
}
