// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"github.com/Sayfargo/gophermart-loyal-service/internal/accrual/goods/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockGoodsCacheAdder creates a new instance of MockGoodsCacheAdder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGoodsCacheAdder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGoodsCacheAdder {
	mock := &MockGoodsCacheAdder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGoodsCacheAdder is an autogenerated mock type for the GoodsCacheAdder type
type MockGoodsCacheAdder struct {
	mock.Mock
}

type MockGoodsCacheAdder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGoodsCacheAdder) EXPECT() *MockGoodsCacheAdder_Expecter {
	return &MockGoodsCacheAdder_Expecter{mock: &_m.Mock}
}

// Add provides a mock function for the type MockGoodsCacheAdder
func (_mock *MockGoodsCacheAdder) Add(rule model.GoodsInfo) {
	_mock.Called(rule)
	return
}

// MockGoodsCacheAdder_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockGoodsCacheAdder_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - rule model.GoodsInfo
func (_e *MockGoodsCacheAdder_Expecter) Add(rule any) *MockGoodsCacheAdder_Add_Call {
	return &MockGoodsCacheAdder_Add_Call{Call: _e.mock.On("Add", rule)}
}

func (_c *MockGoodsCacheAdder_Add_Call) Run(run func(rule model.GoodsInfo)) *MockGoodsCacheAdder_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 model.GoodsInfo
		if args[0] != nil {
			arg0 = args[0].(model.GoodsInfo)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockGoodsCacheAdder_Add_Call) Return() *MockGoodsCacheAdder_Add_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockGoodsCacheAdder_Add_Call) RunAndReturn(run func(rule model.GoodsInfo)) *MockGoodsCacheAdder_Add_Call {
	_c.Run(run)
	return _c
}
