// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"context"

	"github.com/Sayfargo/gophermart-loyal-service/internal/accrual/goods/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockGoodsRepository creates a new instance of MockGoodsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGoodsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGoodsRepository {
	mock := &MockGoodsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGoodsRepository is an autogenerated mock type for the GoodsRepository type
type MockGoodsRepository struct {
	mock.Mock
}

type MockGoodsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGoodsRepository) EXPECT() *MockGoodsRepository_Expecter {
	return &MockGoodsRepository_Expecter{mock: &_m.Mock}
}

// RegisterGoods provides a mock function for the type MockGoodsRepository
func (_mock *MockGoodsRepository) RegisterGoods(ctx context.Context, goods model.GoodsInfo) error {
	ret := _mock.Called(ctx, goods)

	if len(ret) == 0 {
		panic("no return value specified for RegisterGoods")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.GoodsInfo) error); ok {
		r0 = returnFunc(ctx, goods)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGoodsRepository_RegisterGoods_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterGoods'
type MockGoodsRepository_RegisterGoods_Call struct {
	*mock.Call
}

// RegisterGoods is a helper method to define mock.On call
//   - ctx context.Context
//   - goods model.GoodsInfo
func (_e *MockGoodsRepository_Expecter) RegisterGoods(ctx any, goods any) *MockGoodsRepository_RegisterGoods_Call {
	return &MockGoodsRepository_RegisterGoods_Call{Call: _e.mock.On("RegisterGoods", ctx, goods)}
}

func (_c *MockGoodsRepository_RegisterGoods_Call) Run(run func(ctx context.Context, goods model.GoodsInfo)) *MockGoodsRepository_RegisterGoods_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.GoodsInfo
		if args[1] != nil {
			arg1 = args[1].(model.GoodsInfo)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGoodsRepository_RegisterGoods_Call) Return(err error) *MockGoodsRepository_RegisterGoods_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGoodsRepository_RegisterGoods_Call) RunAndReturn(run func(ctx context.Context, goods model.GoodsInfo) error) *MockGoodsRepository_RegisterGoods_Call {
	_c.Call.Return(run)
	return _c
}
